import { locationServices, type LocationService } from "@/lib/location-services";
import { michiganCities, slugify } from "@/lib/locations";

export function LocationServicePage({ service, city }: { service: LocationService; city?: string }) {
  const place = city ?? "Michigan";
  const headline = `${service.name} in ${place}`;
  const cityLinks = city ? michiganCities.filter((item) => item !== city).slice(0, 12) : michiganCities;
  return <main>
    <header className="header"><a className="brand" href="/" aria-label="Northline Technology home"><span className="brandMark">N</span><span>NORTHLINE<small>TECHNOLOGY</small></span></a><nav className="nav serviceNav" aria-label="Main navigation"><a href="/#services">ALL SERVICES</a><a href="/#why">WHY NORTHLINE</a><a className="navCta" href="#contact">CONTACT US</a></nav></header>
    <section className="serviceHero"><div className="serviceHeroInner"><div><p className="eyebrow">{service.short.toUpperCase()} · {place.toUpperCase()}</p><h1>{headline}</h1><p>{city ? `${service.intro} Northline helps organizations in ${city} turn technical priorities into practical business outcomes.` : service.intro}</p><a className="button primary" href="#contact">TALK TO AN EXPERT <b>→</b></a></div><div className="servicePhoto" style={{backgroundImage:`linear-gradient(#071a2f18,#071a2f44),url('${service.image}')`}}><span>{service.icon}</span></div></div></section>
    <section className="serviceBenefits"><div><p className="eyebrow orange">THE OUTCOME</p><h2>{city ? `A stronger technology foundation for ${city} organizations.` : "Technology that supports the way you work."}</h2></div><ul>{service.benefits.map((benefit)=><li key={benefit}><i>✓</i>{benefit}</li>)}</ul></section>
    <section className="section serviceDetails"><div className="sectionLead"><p className="eyebrow orange">WHAT’S INCLUDED</p><h2>A complete approach to {service.short.toLowerCase()}.</h2></div><div className="featureGrid">{service.features.map((feature,index)=><article key={feature.title}><span>0{index+1}</span><h3>{feature.title}</h3><p>{feature.copy}</p></article>)}</div></section>
    <section className="serviceProcess"><div><p className="eyebrow orange">HOW WE WORK</p><h2>A clear path from today’s challenges to tomorrow’s goals.</h2></div><ol>{service.process.map((step,index)=><li key={step.title}><span>{index+1}</span><div><h3>{step.title}</h3><p>{step.copy}</p></div></li>)}</ol></section>
    <section className="section locationDirectory"><div className="sectionLead"><p className="eyebrow orange">MICHIGAN SERVICE AREA</p><h2>{city ? `More Michigan locations for ${service.short.toLowerCase()}` : `${service.short} in every Michigan city`}</h2><p>{city ? `Explore the same Northline service for organizations across Michigan, or return to the statewide ${service.short.toLowerCase()} page.` : "Choose your city for a local service overview and a direct path to the Northline team."}</p></div>{city && <a className="statewideLink" href={`/${service.slug}`}>VIEW STATEWIDE SERVICE →</a>}<div className="cityGrid">{cityLinks.map((item)=><a key={item} href={`/${service.slug}/${service.slug.replace(/-michigan$/, "")}-${slugify(item)}-michigan/`}>{item}</a>)}</div></section>
    <section className="section serviceFaq"><div><p className="eyebrow orange">COMMON QUESTIONS</p><h2>{place} {service.short.toLowerCase()} answers.</h2></div><div><article><h3>Do you serve organizations in {place}?</h3><p>Yes. Northline serves businesses and organizations throughout Michigan with remote delivery, local coordination, and onsite support when the work calls for it.</p></article><article><h3>How do we get started?</h3><p>We begin with a focused conversation about your environment, goals, risks, and timing, then recommend a clear next step.</p></article></div></section>
    <section className="cta" id="contact"><p className="eyebrow">LET’S TALK</p><h2>Make your next technology decision with confidence.</h2><p>Tell us what you are working through. We’ll help identify a clear, practical next step.</p><a className="button light" href="mailto:hello@northlinetechnology.com">SCHEDULE A CONVERSATION <b>→</b></a></section>
    <footer><div className="footerBrand"><a className="brand" href="/"><span className="brandMark">N</span><span>NORTHLINE<small>TECHNOLOGY</small></span></a><p>Michigan-based managed technology services focused on clear outcomes, resilient systems, and dependable support.</p></div><div><b>SERVICES</b>{locationServices.slice(0,4).map((item)=><a key={item.slug} href={`/${item.slug}`}>{item.short}</a>)}</div><div><b>MORE SERVICES</b>{locationServices.slice(4).map((item)=><a key={item.slug} href={`/${item.slug}`}>{item.short}</a>)}</div><div><b>CONTACT</b><a href="mailto:hello@northlinetechnology.com">hello@northlinetechnology.com</a><span>Serving businesses across Michigan</span></div><p className="copyright">© 2026 Northline Technology. All rights reserved.</p></footer>
  </main>;
}
